// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExecuteShortcut(arg1) {
  return window['go']['main']['App']['ExecuteShortcut'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetCurrentImageInfo() {
  return window['go']['main']['App']['GetCurrentImageInfo']();
}

export function GetImageCounts() {
  return window['go']['main']['App']['GetImageCounts']();
}

export function GetLastWorkingDir() {
  return window['go']['main']['App']['GetLastWorkingDir']();
}

export function GetNearbyImages(arg1) {
  return window['go']['main']['App']['GetNearbyImages'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetUndoCount() {
  return window['go']['main']['App']['GetUndoCount']();
}

export function GetWorkingDirectory() {
  return window['go']['main']['App']['GetWorkingDirectory']();
}

export function GoToImage(arg1) {
  return window['go']['main']['App']['GoToImage'](arg1);
}

export function NextImage() {
  return window['go']['main']['App']['NextImage']();
}

export function PreviousImage() {
  return window['go']['main']['App']['PreviousImage']();
}

export function SelectDestinationFolder() {
  return window['go']['main']['App']['SelectDestinationFolder']();
}

export function SelectWorkingDirectory() {
  return window['go']['main']['App']['SelectWorkingDirectory']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetWorkingDirectory(arg1) {
  return window['go']['main']['App']['SetWorkingDirectory'](arg1);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
