// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DuplicateProfile(arg1) {
  return window['go']['main']['App']['DuplicateProfile'](arg1);
}

export function ExecuteFunctionButton(arg1) {
  return window['go']['main']['App']['ExecuteFunctionButton'](arg1);
}

export function ExecuteMultiLabel(arg1) {
  return window['go']['main']['App']['ExecuteMultiLabel'](arg1);
}

export function ExecuteShortcut(arg1) {
  return window['go']['main']['App']['ExecuteShortcut'](arg1);
}

export function ExecuteShortcutByIndex(arg1) {
  return window['go']['main']['App']['ExecuteShortcutByIndex'](arg1);
}

export function GetActiveProfile() {
  return window['go']['main']['App']['GetActiveProfile']();
}

export function GetCurrentImageInfo() {
  return window['go']['main']['App']['GetCurrentImageInfo']();
}

export function GetExtraImagePath() {
  return window['go']['main']['App']['GetExtraImagePath']();
}

export function GetImageCounts() {
  return window['go']['main']['App']['GetImageCounts']();
}

export function GetImageLabels(arg1) {
  return window['go']['main']['App']['GetImageLabels'](arg1);
}

export function GetImageMetadata() {
  return window['go']['main']['App']['GetImageMetadata']();
}

export function GetInitialFile() {
  return window['go']['main']['App']['GetInitialFile']();
}

export function GetLastWorkingDir() {
  return window['go']['main']['App']['GetLastWorkingDir']();
}

export function GetNearbyImages(arg1) {
  return window['go']['main']['App']['GetNearbyImages'](arg1);
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetUndoCount() {
  return window['go']['main']['App']['GetUndoCount']();
}

export function GetViewMode() {
  return window['go']['main']['App']['GetViewMode']();
}

export function GetWorkingDirectory() {
  return window['go']['main']['App']['GetWorkingDirectory']();
}

export function GoToImage(arg1) {
  return window['go']['main']['App']['GoToImage'](arg1);
}

export function HandleFileOpen(arg1) {
  return window['go']['main']['App']['HandleFileOpen'](arg1);
}

export function NextImage() {
  return window['go']['main']['App']['NextImage']();
}

export function OpenImageFile(arg1) {
  return window['go']['main']['App']['OpenImageFile'](arg1);
}

export function PreviousImage() {
  return window['go']['main']['App']['PreviousImage']();
}

export function ResetAnnotations() {
  return window['go']['main']['App']['ResetAnnotations']();
}

export function SelectDestinationFolder() {
  return window['go']['main']['App']['SelectDestinationFolder']();
}

export function SelectWorkingDirectory() {
  return window['go']['main']['App']['SelectWorkingDirectory']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetInitialFile(arg1) {
  return window['go']['main']['App']['SetInitialFile'](arg1);
}

export function SetViewMode(arg1) {
  return window['go']['main']['App']['SetViewMode'](arg1);
}

export function SetWorkingDirectory(arg1) {
  return window['go']['main']['App']['SetWorkingDirectory'](arg1);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdateProfile(arg1) {
  return window['go']['main']['App']['UpdateProfile'](arg1);
}
