// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateProfile(arg1:string):Promise<models.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExecuteFunctionButton(arg1:number):Promise<void>;

export function ExecuteMultiLabel(arg1:Array<string>):Promise<models.ImageInfo>;

export function ExecuteShortcut(arg1:string):Promise<models.ImageInfo>;

export function GetActiveProfile():Promise<models.Profile>;

export function GetCurrentImageInfo():Promise<models.ImageInfo>;

export function GetImageCounts():Promise<models.ImageCounts>;

export function GetImageLabels(arg1:string):Promise<Array<string>>;

export function GetLastWorkingDir():Promise<string>;

export function GetNearbyImages(arg1:number):Promise<Array<models.ImageInfo>>;

export function GetProfiles():Promise<Array<models.Profile>>;

export function GetUndoCount():Promise<number>;

export function GetViewMode():Promise<string>;

export function GetWorkingDirectory():Promise<string>;

export function GoToImage(arg1:number):Promise<models.ImageInfo>;

export function NextImage():Promise<models.ImageInfo>;

export function PreviousImage():Promise<models.ImageInfo>;

export function SelectDestinationFolder():Promise<string>;

export function SelectWorkingDirectory():Promise<string>;

export function SetActiveProfile(arg1:string):Promise<void>;

export function SetViewMode(arg1:string):Promise<models.ImageInfo>;

export function SetWorkingDirectory(arg1:string):Promise<void>;

export function Undo():Promise<models.ImageInfo>;

export function UpdateProfile(arg1:models.Profile):Promise<void>;
